

import Home from "./components/welcome.jsx";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    name:'viewport',
    content:'width=device-width, initial-scale=1.0'
  }

export default function Homepage() {



    return (
        <>

            
            <Home></Home>
        </>
    )
}